In [12]:
import tensorflow as tf
import numpy as np

In [6]:
with tf.Session() as session: # "with ... as ..."" automatically close file "f"  
    x = tf.placeholder(tf.float32,[1],name="x")
    y = tf.placeholder(tf.float32,[1],name="y")
    z = tf.constant(1.0)
    y = x * z
    x_in = [100]
    y_output = session.run([y],{x:x_in})
    print(y_output)

[array([100.], dtype=float32)]


In [10]:
scalar = tf.constant(100)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])

print(scalar.get_shape())  
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())
with tf.Session() as sess:
    print(vector.get_shape())
    print(sess.run(vector))

()
(5,)
(2, 3)
(3, 3, 1)
(5,)
[1 2 3 4 5]


In [13]:
tensor_2d = np.array([(1,2,3),(4,5,6),(7,8,9)])
tensor_2d = tf.Variable(tensor_2d)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(tensor_2d.get_shape())
    print(sess.run(tensor_2d))

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
interactive_session = tf.InteractiveSession()
tensor = np.array([1,2,3,4,5])
tensor = tf.constant(tensor)
print(tensor.eval()) 
interactive_session.close()

[1 2 3 4 5]


In [16]:
tensor_3d = np.array([[[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8]],\
                      [[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],\
                      [[18, 19, 20],[21, 22, 23],[24, 25, 26]]])
tensor_3d = tf.convert_to_tensor(tensor_3d, dtype=tf.float64)
with tf.Session() as sess:
    print(tensor_3d.get_shape())
    print(sess.run(tensor_3d))

(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]
